### ISSUE TITLE
Track Changes with GitHub

### ISSUE THREAD

**Issue by kemitchell** [kemitchell/privacynotice#4]
Add option to link to GitHub for edit history.

**Comment by kemitchell** [comment]
#3 may have closed this. I'm not sure that anything beyond a URL where users can review changes is needed for GitHub in particular.

**Comment by anseljh** [comment]
It entails more machinery, but I think pointing to releases is better than simple commit history. Commits don't get published and become effective immediately.

**Comment by kemitchell** [comment]
Perhaps we add a hint that if myco/privacy is your notice, use myco/privacy/releases as the archive URL and release accordingly.

**Comment by anseljh** [comment]
:+1:
